---
title: "Causal Inference ITE"
author: "Cathy Shi"
date: "10/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(PSweight)
library(grf)
library(Matching)
library(bartCause)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r RMSE function}
rmse <- function(y, ypred) {
  sqrt(sum((y - ypred)^2)/length(y))
}

```

```{r readfile}
data = read.csv("rhc.csv")
rhc = data %>% 
  dplyr::select(-1) %>% 
  mutate_at(c(1, 3,4,6:19, 21, 22), as.factor) #
rhc_no_outcome = rhc %>% 
  dplyr::select(-53)
#str(rhc)  
```

```{r}
library(splitTools)
set.seed(2022)
inds <- partition(rhc$treatment, p = c(train = 1/3, valid = 1/3, test = 1/3))

train <- rhc[inds$train, ]
valid <- rhc[inds$valid, ]
test <- rhc[inds$test, ]
```

# Design: Matching
```{r}
X = train %>% dplyr::select(-1)
X1 = model.matrix(dth30~., X)
Y = train %>% dplyr::select(53) %>% unlist() %>% as.numeric()
W = train %>% dplyr::select(1) %>% unlist() %>% as.numeric()-1

X.test = test %>% dplyr::select(-1)
X1.test = model.matrix(dth30~., X.test)
Y.test = train %>% dplyr::select(53) %>% unlist() %>% as.numeric()
W.test = train %>% dplyr::select(1) %>% unlist() %>% as.numeric()-1


#matching method
matched <- Match(Y, Tr = W, X1, X1, estimand = "ATC")
#summary(matched)
X_m = matched$mdata$X 
Y_m = matched$mdata$Y
W_m = matched$mdata$Tr
matchdata = data.frame(Y_m, W_m, X_m)
summary(matched)
#CART model with matching:
tau.forest_match <- causal_forest(X_m, Y_m, W_m)
pred1 = predict(tau.forest_match, X1.test)
#ITE:
tau.hat <- predict(tau.forest_match)$predictions

#Linear model with matching:
model_matched <- lm(dth30 ~ treatment, data = train)
model_matched %>% summary()
```

```{r}
#BART with matching
bart_match = bartc(Y_m, W_m, X_m, data = matchdata,  method.rsp = "bart",
      method.trt ="bart",
      estimand   = "atc")
#predict(bart_match)
```

# Design: weighting

```{r propensity score}
LG_ps <- glm(treatment ~ . -dth30, family = "binomial", data = rhc)
est_ps <- fitted.values(LG_ps)
df_ps <- cbind(est_ps,rhc[,2:53]) %>% as.data.frame()
df_ps <- broom::augment_columns(LG_ps,rhc, type.predict = "response")
df_ps <- df_ps %>%
  mutate(propensity = .fitted) %>%
  mutate(treat_num = ifelse(as.logical(treatment), 1, 0)) %>%
  mutate(ipw = treat_num/propensity + (1 - treat_num)/(1 - propensity))
prop_score = df_ps$propensity
```

```{r}
#CART model with weighting: (weights are propensity scores)
prop_score = data.frame(prop_score = prop_score)
pro_score_train = prop_score[inds$train, ]
tau.forest_weight <- causal_forest(X1, Y, W, sample.weights = pro_score_train)
pred2 = predict(tau.forest_weight, X1.test)
#ITE:
tau.hat.weight <- predict(tau.forest_weight)$predictions
```

```{r}
#BART with weights
bart_weight = bartc(Y, W, X1, data = train,  method.rsp = "bart",
      method.trt ="bart", weight = pro_score_train,
      estimand   = "atc")
#pred4 = predict(bart_weight, test)
pred4  = bart_weight$mu.hat.cf
dim(pred4)
```


```{r model comparison}
rmse.match.cart = rmse(Y.test, pred1) #better
rmse.weight.cart = rmse(Y.test, pred2)
rmse.match.bart = 
rmse.weight.bart =   
```




 
